source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'slim'

gem 'puma'

gem 'pry'
gem 'pry-nav'
gem 'activesupport', require: 'active_support/all'

# litecable deps
gem "websocket", "~> 1.2.4"
